name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: demoblaze
        run: npm ci

      - name: Install Playwright browsers
        working-directory: demoblaze
        run: npx playwright install --with-deps

      # Install Allure Node reporter
      - name: Install Allure Reporter
        working-directory: demoblaze
        run: npm i -D allure-playwright

      # Run Playwright tests with Allure output
      - name: Run tests
        working-directory: demoblaze
        run: npx playwright test --reporter=line,allure-playwright

      # Install Allure Command-Line
      - name: Install Allure CLI
        run:  |
          sudo apt-get update
          sudo apt-get install -y unzip default-jre
          wget https://github.com/allure-framework/allure2/releases/download/2.29.0/allure-2.29.0.zip
          unzip allure-2.29.0.zip
          sudo mv allure-2.29.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure
          allure --version

      # Generate Allure Report
      - name: Generate Allure Report
        if: always()
        working-directory: demoblaze
        run: allure generate allure-results --clean -o allure-report

      # Upload Playwright HTML report
      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: demoblaze/playwright-report

      # Upload Allure results
      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: demoblaze/allure-results

      # Upload Allure HTML report
      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: demoblaze/allure-report



